In [2]:
import pandas as pd
test_mapped_to_PID = pd.read_pickle("../lib/test_playlist_mappings.pkl")

In [6]:
len(test_mapped_to_PID)

5550

In [7]:
train_mapped_to_PID = pd.read_pickle("../lib/train_playlist_mappings.pkl")
len(train_mapped_to_PID)

105450

In [8]:
tracks = pd.read_pickle("../lib/tracks.pkl")

In [9]:
tracks.head()

pos        artist_name  \
tid                                              
0UaMYEvWZi0ZqiDOoHU3YI    0      Missy Elliott   
6I9VzXrHxO9rA9A5euc8Ak    1     Britney Spears   
0WqIKmW4BTrj3eJFmnCKMv    2            Beyoncé   
1AWQoqb9bSvzTjaLralEkT    3  Justin Timberlake   
1lzr43nnXAijIGYnCT8M8H    4             Shaggy   

                                                   track_uri  \
tid                                                            
0UaMYEvWZi0ZqiDOoHU3YI  spotify:track:0UaMYEvWZi0ZqiDOoHU3YI   
6I9VzXrHxO9rA9A5euc8Ak  spotify:track:6I9VzXrHxO9rA9A5euc8Ak   
0WqIKmW4BTrj3eJFmnCKMv  spotify:track:0WqIKmW4BTrj3eJFmnCKMv   
1AWQoqb9bSvzTjaLralEkT  spotify:track:1AWQoqb9bSvzTjaLralEkT   
1lzr43nnXAijIGYnCT8M8H  spotify:track:1lzr43nnXAijIGYnCT8M8H   

                                                   artist_uri  \
tid                                                             
0UaMYEvWZi0ZqiDOoHU3YI  spotify:artist:2wIVse2owClT7go1WT98tk   
6I9VzXrHxO9rA9A5euc8Ak  spotify:artist:26dSoYclwsYLMAKD3tpOr4   
0WqIKmW4BTrj3eJFmnCKMv  spotify:artist:6vWDO969PvNqNYHIOW5v0m   
1AWQoqb9bSvzTjaLralEkT  spotify:artist:31TPClRtHm23RisEBtV3X7   
1lzr43nnXAijIGYnCT8M8H  spotify:artist:5EvFsr3kj42KNv97ZEnqij   

                                                        track_name  \
tid                                                                  
0UaMYEvWZi0ZqiDOoHU3YI  Lose Control (feat. Ciara & Fat Man Scoop)   
6I9VzXrHxO9rA9A5euc8Ak                                       Toxic   
0WqIKmW4BTrj3eJFmnCKMv                               Crazy In Love   
1AWQoqb9bSvzTjaLralEkT                              Rock Your Body   
1lzr43nnXAijIGYnCT8M8H                                It Wasn't Me   

                                                   album_uri  duration_ms  \
tid                                                                         
0UaMYEvWZi0ZqiDOoHU3YI  spotify:album:6vV5UrXcfyQD1wu4Qo2I9K       226863   
6I9VzXrHxO9rA9A5euc8Ak  spotify:album:0z7pVBGOD7HCIB7S8eLkLI       198800   
0WqIKmW4BTrj3eJFmnCKMv  spotify:album:25hVFAxTlDvXbx2X2QkUkE       235933   
1AWQoqb9bSvzTjaLralEkT  spotify:album:6QPkyl04rXwTGlGlcYaRoW       267266   
1lzr43nnXAijIGYnCT8M8H  spotify:album:6NmFmPX56pcLBOFMhIiKvF       227600   

                                                          album_name  \
tid                                                                    
0UaMYEvWZi0ZqiDOoHU3YI                                  The Cookbook   
6I9VzXrHxO9rA9A5euc8Ak                                   In The Zone   
0WqIKmW4BTrj3eJFmnCKMv  Dangerously In Love (Alben für die Ewigkeit)   
1AWQoqb9bSvzTjaLralEkT                                     Justified   
1lzr43nnXAijIGYnCT8M8H                                      Hot Shot   

                        sparse_id  
tid                                
0UaMYEvWZi0ZqiDOoHU3YI          0  
6I9VzXrHxO9rA9A5euc8Ak          1  
0WqIKmW4BTrj3eJFmnCKMv          2  
1AWQoqb9bSvzTjaLralEkT          3  
1lzr43nnXAijIGYnCT8M8H          4

In [11]:
import torch
import torch.nn as nn

class CustomEmbedding(nn.Module):
    def __init__(self, vocab_size, embedding_dim, pretrained_weights):
        super(CustomEmbedding, self).__init__()
        self.embedding = nn.Embedding(vocab_size, embedding_dim)
        self.embedding.weight = nn.Parameter(torch.tensor(pretrained_weights, dtype=torch.float32), requires_grad=False)

    def forward(self, input):
        return self.embedding(input)

# Example usage
vocab_size = 3
embedding_dim = 7
pretrained_weights = [[1, 2, 3, 4, 5, 6, 7],
                      [7, 6, 5, 4, 3, 2, 1],
                      [3, 4, 5, 6, 1, 0, 8]]

custom_embedding = CustomEmbedding(vocab_size, embedding_dim, pretrained_weights)

# Test with some input indices
input_indices = torch.tensor([0, 2, 1], dtype=torch.long)
output = custom_embedding(input_indices)

print("Custom Embedding Weights:")
print(custom_embedding.embedding.weight)

print("\nOutput Tensor:")
print(output)


Custom Embedding Weights:
Parameter containing:
tensor([[1., 2., 3., 4., 5., 6., 7.],
        [7., 6., 5., 4., 3., 2., 1.],
        [3., 4., 5., 6., 1., 0., 8.]])

Output Tensor:
tensor([[1., 2., 3., 4., 5., 6., 7.],
        [3., 4., 5., 6., 1., 0., 8.],
        [7., 6., 5., 4., 3., 2., 1.]])


In [14]:
songs = pd.read_pickle("../lib/transformer/songs.pkl")

In [38]:
songs.head(10)

song_embeddings  sparse_ids
0  [0.12076592, -0.13061827, 0.10547258, 0.295583...           3
1  [0.12045901, -0.12947704, 0.09537712, 0.290344...          10
2  [0.13265012, -0.15328889, 0.11759862, 0.339323...          27
3  [0.15164909, -0.1728261, 0.12788892, 0.3898709...          29
4  [0.16455252, -0.18796569, 0.14208663, 0.412101...          32
5  [0.12076617, -0.13904934, 0.10605989, 0.297622...          38
6  [0.09606907, -0.12174158, 0.08373111, 0.230173...          43
7  [0.13353318, -0.15720044, 0.111221194, 0.33338...          50
8  [0.13863409, -0.16314916, 0.12259527, 0.355918...          64
9  [0.10056652, -0.12033994, 0.09314977, 0.250423...          80

In [148]:
sparse_id = songs[songs.index == 5]['sparse_ids'][5]
print(sparse_id)

38


In [150]:
all_tracks = pd.read_pickle("../lib/tracks.pkl")
all_tracks.head()

pos        artist_name  \
tid                                              
0UaMYEvWZi0ZqiDOoHU3YI    0      Missy Elliott   
6I9VzXrHxO9rA9A5euc8Ak    1     Britney Spears   
0WqIKmW4BTrj3eJFmnCKMv    2            Beyoncé   
1AWQoqb9bSvzTjaLralEkT    3  Justin Timberlake   
1lzr43nnXAijIGYnCT8M8H    4             Shaggy   

                                                   track_uri  \
tid                                                            
0UaMYEvWZi0ZqiDOoHU3YI  spotify:track:0UaMYEvWZi0ZqiDOoHU3YI   
6I9VzXrHxO9rA9A5euc8Ak  spotify:track:6I9VzXrHxO9rA9A5euc8Ak   
0WqIKmW4BTrj3eJFmnCKMv  spotify:track:0WqIKmW4BTrj3eJFmnCKMv   
1AWQoqb9bSvzTjaLralEkT  spotify:track:1AWQoqb9bSvzTjaLralEkT   
1lzr43nnXAijIGYnCT8M8H  spotify:track:1lzr43nnXAijIGYnCT8M8H   

                                                   artist_uri  \
tid                                                             
0UaMYEvWZi0ZqiDOoHU3YI  spotify:artist:2wIVse2owClT7go1WT98tk   
6I9VzXrHxO9rA9A5euc8Ak  spotify:artist:26dSoYclwsYLMAKD3tpOr4   
0WqIKmW4BTrj3eJFmnCKMv  spotify:artist:6vWDO969PvNqNYHIOW5v0m   
1AWQoqb9bSvzTjaLralEkT  spotify:artist:31TPClRtHm23RisEBtV3X7   
1lzr43nnXAijIGYnCT8M8H  spotify:artist:5EvFsr3kj42KNv97ZEnqij   

                                                        track_name  \
tid                                                                  
0UaMYEvWZi0ZqiDOoHU3YI  Lose Control (feat. Ciara & Fat Man Scoop)   
6I9VzXrHxO9rA9A5euc8Ak                                       Toxic   
0WqIKmW4BTrj3eJFmnCKMv                               Crazy In Love   
1AWQoqb9bSvzTjaLralEkT                              Rock Your Body   
1lzr43nnXAijIGYnCT8M8H                                It Wasn't Me   

                                                   album_uri  duration_ms  \
tid                                                                         
0UaMYEvWZi0ZqiDOoHU3YI  spotify:album:6vV5UrXcfyQD1wu4Qo2I9K       226863   
6I9VzXrHxO9rA9A5euc8Ak  spotify:album:0z7pVBGOD7HCIB7S8eLkLI       198800   
0WqIKmW4BTrj3eJFmnCKMv  spotify:album:25hVFAxTlDvXbx2X2QkUkE       235933   
1AWQoqb9bSvzTjaLralEkT  spotify:album:6QPkyl04rXwTGlGlcYaRoW       267266   
1lzr43nnXAijIGYnCT8M8H  spotify:album:6NmFmPX56pcLBOFMhIiKvF       227600   

                                                          album_name  \
tid                                                                    
0UaMYEvWZi0ZqiDOoHU3YI                                  The Cookbook   
6I9VzXrHxO9rA9A5euc8Ak                                   In The Zone   
0WqIKmW4BTrj3eJFmnCKMv  Dangerously In Love (Alben für die Ewigkeit)   
1AWQoqb9bSvzTjaLralEkT                                     Justified   
1lzr43nnXAijIGYnCT8M8H                                      Hot Shot   

                        sparse_id  
tid                                
0UaMYEvWZi0ZqiDOoHU3YI          0  
6I9VzXrHxO9rA9A5euc8Ak          1  
0WqIKmW4BTrj3eJFmnCKMv          2  
1AWQoqb9bSvzTjaLralEkT          3  
1lzr43nnXAijIGYnCT8M8H          4

In [153]:
tid = all_tracks[all_tracks['sparse_id'] == sparse_id].index[0]
tid

'7oK9VyNzrYvRFo7nQEYkWN'

In [25]:
import numpy as np

In [27]:
song_embeds = torch.tensor(np.array(songs['song_embeddings'].tolist()))
# song_embeds = torch.tensor(song_embeds)
song_embeds.shape

torch.Size([1857, 256])

In [143]:
import torch.nn.functional as F

class SongAndPlaylistEmbeddings(nn.Embedding):
    """
        Usage: embeddings_lookup = SongAndPlaylistEmbeddings(num_positions=V+1, embedding_dim=256, padding_idx=0)
        - where V is the vocabulary size (ie. the total number of songs), and the +1 is the padding
    """

    def __init__(self,num_positions: int, embedding_dim: int, padding_idx: int) -> None:
        super().__init__(num_positions, embedding_dim, padding_idx=padding_idx)
        self.song_embeddings = pd.read_pickle("../lib/transformer/songs.pkl")
        self.artist_embeddings = pd.read_pickle("../lib/transformer/songs.pkl") #TODO change to actual artists!! this is a placeholder!!
        self.weight = self._lookup_embeddings()

    def _lookup_embeddings(self) -> nn.Parameter:
        song_embeds = torch.tensor(np.array(self.song_embeddings['song_embeddings'].tolist()))
        artist_embeds = torch.tensor(np.array(self.artist_embeddings['song_embeddings'].tolist())) #TODO change to artist_embeddings!!!! placeholder!!

        # element-wise addition of embeddings (should work if they are the same dimension)
        concat_tokens = song_embeds + artist_embeds

        # add CLS first
        CLS_token = torch.mean(concat_tokens, dim=0, keepdim=True)
        concat_tokens_2 = torch.cat([CLS_token, concat_tokens], dim=0)
        # now add padding
        padding_token = torch.zeros([1,256])
        final_embeds = torch.cat([padding_token, concat_tokens_2], dim=0)

        out = nn.Parameter(torch.tensor(final_embeds, dtype=torch.float32), requires_grad=True)

        return out


In [86]:
num_songs_in_vocab = song_embeds.shape[0]
dims = song_embeds.shape[1]
embedding_lookup_table = SongAndPlaylistEmbeddings(num_positions=num_songs_in_vocab, embedding_dim=dims, padding_idx=0)

/var/folders/0v/1rrf835166g6l4b55txmksjm0000gn/T/ipykernel_34301/3513858326.py:29: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  out = nn.Parameter(torch.tensor(final_embeds, dtype=torch.float32), requires_grad=True)


In [87]:
input_indices = torch.tensor([0,1], dtype=torch.long)
embs = embedding_lookup_table(input_indices)
embs[0]

tensor([ 2.4153e-01, -2.6124e-01,  2.1095e-01,  5.9117e-01,  5.0864e-01,
         1.2760e-01,  6.6620e-02,  3.5036e-02,  3.5876e-02,  1.0987e-01,
        -1.8376e-02, -2.3311e-01, -5.4669e-02, -3.3280e-01, -1.9527e-01,
         5.1632e-01, -1.2028e-01,  1.3035e-02, -6.4097e-01,  3.9311e-01,
         2.0761e-01, -7.6196e-02, -1.4890e-01, -2.5316e-01, -2.9524e-01,
         1.6562e-01, -1.0410e-01,  3.5439e-02,  1.8321e-01, -1.6635e-01,
         2.7882e-01,  1.8488e-01,  5.5900e-02, -7.1090e-02,  6.7681e-02,
         2.1222e-01,  5.4493e-01, -3.1783e-01,  2.0890e-01, -2.8956e-02,
         1.2197e-01,  2.8200e-01,  4.8750e-01, -1.1600e-01,  4.2540e-01,
        -2.7720e-01,  1.1697e-01, -2.2295e-01,  5.8427e-01,  5.3018e-04,
        -1.6559e-01,  5.0666e-02,  1.4963e-01,  2.7220e-01, -3.1381e-01,
        -2.8920e-01, -2.2059e-01, -4.8852e-01, -1.4172e-01,  2.9517e-01,
        -6.0118e-01, -3.1716e-01, -1.3030e-01, -3.1005e-02,  5.1227e-01,
        -1.3069e-01,  1.8680e-01,  4.3116e-01, -1.7

In [17]:
song_names_test = np.load("../lib/transformer/song_names_test.npy", allow_pickle=True)
song_names_train_1 = np.load("../lib/transformer/song_names_train_1.npy", allow_pickle=True)

In [19]:
song_names_test

array([list([3515, 4582, 4588, 8048, 9711, 11911, 32988, 57079, 67226, 74459, 75316, 101722, 104068, 104069, 104070, 104071, 104072, 104073, 104074, 104075, 121796, 142818, 163062, 169102, 203895, 203896, 203897, 203898, 203899, 203900, 203901, 203902, 203903, 203904, 203905, 312702, 312703, 312704, 312705, 317435, 317436, 317437, 317438, 317439, 317440, 317441, 317442]),
       list([3, 263, 353, 354, 751, 806, 939, 968, 974, 1322, 1416, 1627, 1646, 1980, 2084, 2137, 2150, 2329, 3065, 3388, 4421, 4715, 5512, 5602, 5604, 5616, 7018, 7892, 8792, 10806, 11593, 12060, 13338, 14204, 22433, 26736, 28151, 55001, 103401, 104142, 117989, 176327, 180653]),
       list([3352, 7491, 7779, 10704, 11635, 13503, 13504, 13506, 13510, 13520, 13809, 14073, 14109, 18003, 20558, 23670, 24262, 27334, 27336, 28194, 28228, 29633, 31587, 36630, 36637, 37625, 39391, 39404, 39524, 49915, 49977, 52314, 52341, 53177, 53684, 53686, 53697, 57736, 58666, 64515, 64567, 68896, 74001, 74004, 74014, 74086, 77867, 85672

In [110]:
playlist_song_sparse_ids = song_names_test[3]
playlist_song_sparse_ids

[14752, 21132, 79071, 116124, 130511, 508339, 674309]

In [124]:
songs_vocab_ids = []
for i in playlist_song_sparse_ids:
    songs_vocab_ids.append(songs[songs['sparse_ids'] == i].index[0] + 2)

padding_and_cls = [0,1]
padding_and_cls.extend(songs_vocab_ids)
full_padded_input = padding_and_cls

len_curr = len(full_padded_input)
if len_curr > 100:
    full_padded_input = full_padded_input[:100]
elif len_curr < 100:
    padding = torch.zeros([1,100-len_curr], dtype=int)
    padding = padding.squeeze(0).tolist()
    full_padded_input.extend(padding)


tensor([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 1, 729, 832, 1306, 1415, 1457, 1786, 1837, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]


In [130]:
import os
import pickle

import torch
import numpy as np
import pandas as pd
import torch.optim as optim
import torch.nn.functional as F
from sklearn.metrics import mean_squared_error
from torch import nn
from torch.utils.data import Dataset

In [138]:
class PlaylistDataset(Dataset):
    def __init__(self, playlist_info_sparse_ids, songs_list):
        self.playlist_info_sparse_ids = playlist_info_sparse_ids
        self.songs_list = songs_list
        
    def __len__(self):
        # should return the number of samples aka the number of 
        return len(self.playlist_info_sparse_ids)
    
    def __getitem__(self, playlist_idx):
        playlist_song_sparse_ids = self.playlist_info_sparse_ids[playlist_idx]
        songs_vocab_ids = []
        for i in playlist_song_sparse_ids:
            # grab the id of the song in the internal vocabulary,
            #  and add 2 to it since the embedding lookup table has the padding and CLS at indices 0 and 1
            songs_vocab_ids.append(self.songs_list[self.songs_list['sparse_ids'] == i].index[0] + 2)

        full_padded_input = [1]
        full_padded_input.extend(songs_vocab_ids)

        len_curr = len(full_padded_input)
        if len_curr > 100:
            full_padded_input = full_padded_input[:100]
        elif len_curr < 100:
            padding = torch.zeros([1,100-len_curr], dtype=int)
            padding = padding.squeeze(0).tolist()
            full_padded_input.extend(padding)
        
        full_padded_input_tensor = torch.tensor(full_padded_input)

        return {"songs": full_padded_input_tensor}

In [139]:
song_names_train = np.load("../lib/transformer/song_names_train_1.npy", allow_pickle=True)
song_names_test = np.load("../lib/transformer/song_names_test.npy", allow_pickle=True)
artist_names_train = np.load("../lib/transformer/song_names_train_1.npy", allow_pickle=True)  #TODO change to artists!! this is a placeholder!!
artist_names_test = np.load("../lib/transformer/song_names_test.npy", allow_pickle=True) #TODO change to artists!! this is a placeholder!!

train_dataset = PlaylistDataset(song_names_train, songs)
test_dataset = PlaylistDataset(song_names_test, songs)

train_dataloader = torch.utils.data.DataLoader(train_dataset, batch_size = 5)
test_dataloader = torch.utils.data.DataLoader(test_dataset, batch_size = 5)

In [142]:
for i, inputs in enumerate(train_dataloader):
    inputs = inputs["songs"]
    if i == 0:
        print(inputs.shape)
    print(inputs)

torch.Size([5, 100])
tensor([[   1,   24,  177,  335,  336,  355,  359,  373,  377,  567,  668,  683,
          735,  737,  818,  846,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0],
        [   1,   30,   50,   52,   77,   94,  124,  261,  300,  370,  472,  479,
          480,  504,  626,  779,  830,  833,  849,  850,  851,  852,  860,  905,
          923, 1086, 1093, 1130, 1150, 1151, 1156, 1162, 1180, 1191, 1207, 1236,
         1249, 1260, 1264, 1265, 1302, 1303, 1325, 132